# -*- coding: utf-8 -*-
"""smartpath.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVXFjZFj1AAIW8kn9JegjQ_rKbmPRniu
"""

# Install (Colab)
!pip install numpy matplotlib scipy

import json
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter
from numpy.polynomial.polynomial import Polynomial
import os

# -----------------------------
# PATH
# -----------------------------
DATA_PATH = "/content"   # adjust if needed

# -----------------------------
# LOAD DATA
# -----------------------------
def load_json(name):
    with open(os.path.join(DATA_PATH, name)) as f:
        return json.load(f)

sample_annotations = load_json("sample_annotation.json")
instances = load_json("instance.json")
categories = load_json("category.json")

print("Data loaded successfully")

# -----------------------------
# LOOKUPS
# -----------------------------
category_lookup = {c["token"]: c["name"] for c in categories}
instance_category = {i["token"]: i["category_token"] for i in instances}

def is_valid_agent(inst):
    cat = category_lookup.get(instance_category.get(inst, ""), "")
    return ("pedestrian" in cat) or ("cycle" in cat)

# -----------------------------
# BUILD TRAJECTORIES
# -----------------------------
tracks = {}

for ann in sample_annotations:
    inst = ann["instance_token"]

    if not is_valid_agent(inst):
        continue

    x, y = ann["translation"][0], ann["translation"][1]

    if inst not in tracks:
        tracks[inst] = []

    tracks[inst].append([x, y])

print(f"Total filtered tracks: {len(tracks)}")

# -----------------------------
# SELECT BEST TRAJECTORY
# -----------------------------
traj = None
max_len = 0

for k in tracks:
    t = np.array(tracks[k])
    if len(t) > max_len:
        max_len = len(t)
        traj = t

if traj is None or len(traj) < 30:
    raise Exception("No valid trajectory found")

print(f"Using trajectory length: {len(traj)}")

# -----------------------------
# SMOOTH TRAJECTORY
# -----------------------------
traj[:,0] = savgol_filter(traj[:,0], 7, 2)
traj[:,1] = savgol_filter(traj[:,1], 7, 2)

# -----------------------------
# SPLIT
# -----------------------------
past = traj[-30:-10]
future_gt = traj[-10:]

# -----------------------------
# WEIGHTED VELOCITY
# -----------------------------
def compute_weighted_velocity(traj):
    velocities = traj[1:] - traj[:-1]
    weights = np.linspace(0.5, 1.5, len(velocities))
    weighted = velocities * weights[:, None]
    return np.mean(weighted, axis=0)

# -----------------------------
# POLYNOMIAL FIT (FIXED)
# -----------------------------
def fit_polynomial(traj):
    t = np.arange(len(traj))
    poly_x = Polynomial.fit(t, traj[:,0], deg=1)  # FIXED DEGREE
    poly_y = Polynomial.fit(t, traj[:,1], deg=1)
    return poly_x, poly_y

# -----------------------------
# FINAL HYBRID PREDICTION
# -----------------------------
def predict_future(traj, steps=10):
    poly_x, poly_y = fit_polynomial(traj)
    vel = compute_weighted_velocity(traj)

    future = []
    last = traj[-1]

    for i in range(1, steps+1):
        t = len(traj) + i

        # Polynomial estimate
        px = poly_x(t)
        py = poly_y(t)

        # Motion estimate
        motion_x = last[0] + vel[0] * i
        motion_y = last[1] + vel[1] * i

        # Blend both (CRITICAL FIX)
        alpha = 0.7
        final_x = alpha * motion_x + (1 - alpha) * px
        final_y = alpha * motion_y + (1 - alpha) * py

        future.append([final_x, final_y])

    return np.array(future)

# -----------------------------
# MULTI-MODAL PREDICTION
# -----------------------------
def multi_path(traj):
    base = predict_future(traj)
    paths = []

    for _ in range(5):
        noise = np.random.normal(0, 0.02, base.shape)
        paths.append(base + noise)

    return paths

pred_paths = multi_path(past)

# -----------------------------
# METRICS
# -----------------------------
def compute_metrics(pred, gt):
    ade = np.mean(np.linalg.norm(pred - gt, axis=1))
    fde = np.linalg.norm(pred[-1] - gt[-1])
    return ade, fde

best_ade = float("inf")
best_path = None

for i, p in enumerate(pred_paths):
    ade, fde = compute_metrics(p, future_gt)
    print(f"Path {i+1} -> ADE: {ade:.3f}, FDE: {fde:.3f}")

    if ade < best_ade:
        best_ade = ade
        best_path = p

confidence = 1 / (best_ade + 1e-6)

print(f"\nBest ADE: {best_ade:.3f}")
print(f"Confidence Score: {confidence:.3f}")

# -----------------------------
# VISUALIZATION
# -----------------------------
plt.figure(figsize=(8,6))

plt.plot(past[:,0], past[:,1], 'bo-', label="Past")
plt.plot(future_gt[:,0], future_gt[:,1], 'gx-', label="Actual Future")

# all predictions
for p in pred_paths:
    plt.plot(p[:,0], p[:,1], 'r--', alpha=0.3)

# best prediction
plt.plot(best_path[:,0], best_path[:,1], 'r-', linewidth=3, label="Best Prediction")

plt.legend()
plt.title("Final Optimized Trajectory Prediction (Hybrid Model)")
plt.xlabel("X")
plt.ylabel("Y")
plt.grid()

plt.show()